version: '2'

services:

  tenant-db:
   build: ./db/
   image: tenant_db
   hostname: tenant_db
   restart: always
   environment:
    - MYSQL_ROOT_PASSWORD=martin
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
#     - MYSQL_DATABASE=tenantdb
   volumes:
    - /opt/mysql_data:/var/lib/mysql
   ports:
    - "3306:3306"



